### PR TITLE
updates to use pytest runner

### PR DESCRIPTION
**Pull request by bhgrant8**

### CODE REVIEW

**Comment by MikeTheCanuck** [comment]
Looks like the attempt to install `aswcli` is now failing in a novel way:

```
Installing collected packages: colorama, pyasn1, rsa, futures, docutils, jmespath, six, python-dateutil, botocore, s3transfer, PyYAML, awscli
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/colorama'
```

**Comment by BrianHGrant** [comment]
Yup, gonna try to update to python3

**Comment by MikeTheCanuck** [comment]
Also possible that this or something like it could quickly bypass this "problem":
https://github.com/aws/aws-cli/issues/1980

**Comment by bhgrant8** [comment]
closing as stale

**Pull request closed without merging**
